image:
  file: .gitpod.Dockerfile

tasks:
  - name: Futurenet
    init: |
      docker pull stellar/quickstart:soroban-dev@sha256:8a99332f834ca82e3ac1418143736af59b5288e792d1c4278d6c547c6ed8da3b
    command: |
      docker run --rm -it \
      -p 8000:8000 \
      --name stellar \
      stellar/quickstart:soroban-dev@sha256:8a99332f834ca82e3ac1418143736af59b5288e792d1c4278d6c547c6ed8da3b \
      --futurenet \
      --enable-soroban-rpc
  - name: "Albedo Signer"
    command: |
      cd ~/.local/_client
      clear
      npm run start
  - name: CLI - Futurenet
    env:
      SOROBAN_RPC_URL: "https://rpc-futurenet.stellar.org:443"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Future Network ; October 2022"
    command: |
      source ~/.local/bash-hook
      clear
  - name: CLI - Sandbox
    init: |
      cargo clean
      cargo fetch
      cargo build --package soroban-hello-world-contract --target wasm32-unknown-unknown --release
      cargo test --package soroban-hello-world-contract
    command: |
      if [[ ${QUEST} ]]
      then
        gp open quests/${QUEST}*/README.md
      else
        gp open README.md
      fi
      clear

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - rust-lang.rust-analyzer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: true
    addBadge: true

ports:
  - name: Futurenet
    port: 8000
    visibility: public
    onOpen: ignore
  - name: Albedo Signer
    port: 3000
    visibility: public
    onOpen: ignore
  - port: 4226
    visibility: private
    onOpen: ignore
