image:
  file: .gitpod.Dockerfile

tasks:
  - name: Testnet
    init: |
      docker pull stellar/quickstart:testing
    command: |
      docker run --rm -i \
      -p 8000:8000 \
      --name stellar \
      stellar/quickstart:testing \
      --testnet \
      --enable-soroban-rpc
  - name: "Albedo Signer"
    command: |
      cd ~/.local/_client
      clear
      npm run start
  - name: CLI - Testnet
    env:
      STELLAR_RPC_URL: "https://soroban-testnet.stellar.org"
      STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
    init: |
      cargo clean
      cargo fetch
      stellar contract build --package soroban-hello-world-contract
      cargo test --package soroban-hello-world-contract
    command: |
      source ~/.local/bash-hook
      if [[ ${QUEST} ]]
      then
        gp open quests/${QUEST}*/README.md
      else
        gp open README.md
      fi
      clear

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - rust-lang.rust-analyzer

ports:
  - name: Testnet
    port: 8000
    visibility: public
    onOpen: ignore
  - name: Albedo Signer
    port: 3000
    visibility: public
    onOpen: ignore
  - port: 4226
    visibility: private
    onOpen: ignore
