# Use the official Rust image as the base image
FROM mcr.microsoft.com/devcontainers/rust:bullseye

USER vscode

# Set the working directory
WORKDIR /workspace

# Expose port 8000 for web development
EXPOSE 8000